extends RefCounted
## GENERATED by tools/tree_data.mjs from design/upgrade_trees.md. Edit the design file and re-run
## the generator; don't edit this file by hand.
##
## Per tower: `tiers` (the trunk) and three `branches` (a, b, c). Each branch has four `nodes`
## (the first is the specialization) and a `mastery`. A node's `set` values replace the stat and
## its `add` values add to it. The specialization and mastery only use `set`.

const ORDER := ["arrow", "cannon", "frost", "sniper", "tesla", "laser", "missile", "amp", "flak", "sensor", "gravity", "nullifier", "nova", "drones", "scrap"]

const TREES := {
	"arrow": {
		"name": "Pulse Turret",
		"key": "1",
		"tiers": [
			{
				"name": "Pulse Turret",
				"cost": 50,
				"blurb": "A compact turret that fires rapid energy bolts at one target, air or ground.",
				"set": {
					"damage": 9.0,
					"range": 140.0,
					"rate": 2.0,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 70,
				"blurb": "Twin emitters: harder-hitting bolts, fired faster and a little further.",
				"set": {
					"damage": 15.0,
					"range": 152.0,
					"rate": 2.4,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "gatling",
				"attack": false,
				"nodes": [
					{
						"name": "Gatling Pulse",
						"cost": 140,
						"blurb": "Four spinning barrels: double the rate of fire.",
						"set": {
							"damage": 16.0,
							"range": 160.0,
							"rate": 5.0,
						},
						"add": {},
					},
					{
						"name": "Cooled Barrels",
						"cost": 170,
						"blurb": "Liquid cooling keeps the barrels spinning.",
						"set": {},
						"add": {
							"rate": 0.4,
						},
					},
					{
						"name": "Hardened Bolts",
						"cost": 200,
						"blurb": "Denser bolt casings that hit harder on every one of the many shots.",
						"set": {},
						"add": {
							"damage": 3.0,
						},
					},
					{
						"name": "Belt Feed",
						"cost": 300,
						"blurb": "A continuous ammo belt and a raised mount: faster fire, more damage and longer reach.",
						"set": {},
						"add": {
							"range": 10.0,
							"rate": 0.6,
							"damage": 2.0,
						},
					},
				],
				"mastery": {
					"name": "Storm Gatling",
					"cost": 410,
					"blurb": "Twin ammo feeds: every volley also fires at a second target.",
					"set": {
						"damage": 24.0,
						"range": 175.0,
						"rate": 7.0,
						"multishot": 2.0,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "shredder",
				"attack": false,
				"nodes": [
					{
						"name": "Shredder",
						"cost": 140,
						"blurb": "Each hit permanently strips 1 armor.",
						"set": {
							"damage": 28.0,
							"range": 165.0,
							"rate": 3.0,
							"shred": 1.0,
							"shred_max": 8.0,
						},
						"add": {},
					},
					{
						"name": "Serrated Rounds",
						"cost": 170,
						"blurb": "Saw-toothed rounds that bite deeper into the plating they've already stripped.",
						"set": {},
						"add": {
							"damage": 4.0,
						},
					},
					{
						"name": "Tungsten Core",
						"cost": 200,
						"blurb": "Strips up to 10 armor.",
						"set": {},
						"add": {
							"shred_max": 2.0,
						},
					},
					{
						"name": "Fracture Rounds",
						"cost": 300,
						"blurb": "Rounds that shatter on impact: more damage, faster cycling and a longer reach.",
						"set": {},
						"add": {
							"rate": 0.3,
							"damage": 6.0,
							"range": 10.0,
						},
					},
				],
				"mastery": {
					"name": "Disintegrator",
					"cost": 410,
					"blurb": "Each hit strips 2 armor. Dreadnoughts come apart.",
					"set": {
						"damage": 52.0,
						"range": 180.0,
						"rate": 3.6,
						"shred": 2.0,
						"shred_max": 14.0,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "flechette",
				"attack": true,
				"nodes": [
					{
						"name": "Flechette",
						"cost": 140,
						"blurb": "Fires a cone of flechettes that hits every enemy in the arc, air and ground.",
						"set": {
							"damage": 11.0,
							"pellets": 6.0,
							"range": 130.0,
							"rate": 1.6,
							"cone": 45.0,
						},
						"add": {},
					},
					{
						"name": "Wider Choke",
						"cost": 170,
						"blurb": "A wider choke spreads the flechettes over a broader arc.",
						"set": {},
						"add": {
							"cone": 5.0,
						},
					},
					{
						"name": "Dense Pack",
						"cost": 200,
						"blurb": "Packs one more flechette into every shell.",
						"set": {},
						"add": {
							"pellets": 1.0,
						},
					},
					{
						"name": "Rapid Pump",
						"cost": 300,
						"blurb": "A pump-action loader and heavier darts: faster volleys that hit harder.",
						"set": {},
						"add": {
							"damage": 3.0,
							"rate": 0.3,
						},
					},
				],
				"mastery": {
					"name": "Hailstorm",
					"cost": 410,
					"blurb": "A wider cone, and flechettes slip past barriers to hit the hull directly.",
					"set": {
						"damage": 16.0,
						"pellets": 9.0,
						"range": 145.0,
						"rate": 2.0,
						"cone": 60.0,
						"bypass_shield": true,
					},
					"add": {},
				},
			},
		],
	},
	"cannon": {
		"name": "Plasma Mortar",
		"key": "2",
		"tiers": [
			{
				"name": "Plasma Mortar",
				"cost": 90,
				"blurb": "Lobs plasma shells that burst over an area, hitting every ground enemy in the blast.",
				"set": {
					"damage": 22.0,
					"range": 130.0,
					"rate": 0.7,
					"splash": 55.0,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 120,
				"blurb": "Bigger shells: more damage, a wider blast and a little more range.",
				"set": {
					"damage": 40.0,
					"range": 140.0,
					"rate": 0.75,
					"splash": 65.0,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "siege",
				"attack": false,
				"nodes": [
					{
						"name": "Siege Mortar",
						"cost": 210,
						"blurb": "Heavier shells, a much bigger blast and longer range.",
						"set": {
							"damage": 80.0,
							"range": 165.0,
							"rate": 0.8,
							"splash": 90.0,
						},
						"add": {},
					},
					{
						"name": "Long Barrel",
						"cost": 250,
						"blurb": "A longer barrel reaches further down the lane.",
						"set": {},
						"add": {
							"range": 10.0,
						},
					},
					{
						"name": "Heavy Payload",
						"cost": 300,
						"blurb": "Heavier shells for much bigger hits.",
						"set": {},
						"add": {
							"damage": 20.0,
						},
					},
					{
						"name": "Auto-Loader",
						"cost": 450,
						"blurb": "An automatic loader and wider-dispersal shells: faster fire and a bigger blast.",
						"set": {},
						"add": {
							"splash": 8.0,
							"rate": 0.1,
						},
					},
				],
				"mastery": {
					"name": "Earthshaker",
					"cost": 510,
					"blurb": "Shockwave shells stun everything in the blast (bosses 0.12 s).",
					"set": {
						"damage": 150.0,
						"range": 190.0,
						"rate": 0.95,
						"splash": 110.0,
						"stun": 0.4,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "napalm",
				"attack": false,
				"nodes": [
					{
						"name": "Plasma Burn",
						"cost": 210,
						"blurb": "Leaves a plasma pool that burns ground enemies, ignoring armor.",
						"set": {
							"damage": 55.0,
							"range": 150.0,
							"splash": 70.0,
							"burn_dps": 32.0,
							"burn_time": 3.0,
						},
						"add": {},
					},
					{
						"name": "Hotter Plasma",
						"cost": 250,
						"blurb": "Hotter plasma: the pools burn harder.",
						"set": {},
						"add": {
							"burn_dps": 8.0,
						},
					},
					{
						"name": "Sticky Gel",
						"cost": 300,
						"blurb": "A sticky gel binder keeps the pools burning for an extra second.",
						"set": {},
						"add": {
							"burn_time": 1.0,
						},
					},
					{
						"name": "Pressurized Tanks",
						"cost": 450,
						"blurb": "Pressurized tanks: bigger shells, wider pools and hotter burns.",
						"set": {},
						"add": {
							"splash": 6.0,
							"damage": 15.0,
							"burn_dps": 8.0,
						},
					},
				],
				"mastery": {
					"name": "Inferno Mortar",
					"cost": 510,
					"blurb": "White-hot pools that burn longer and hotter.",
					"set": {
						"damage": 90.0,
						"range": 165.0,
						"splash": 85.0,
						"burn_dps": 65.0,
						"burn_time": 5.0,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "buster",
				"attack": false,
				"nodes": [
					{
						"name": "Bunker Buster",
						"cost": 210,
						"blurb": "Delayed-fuse shells detonate underground: they hit burrowed enemies and strip armor from everything in the blast.",
						"set": {
							"damage": 70.0,
							"range": 150.0,
							"rate": 0.7,
							"splash": 60.0,
							"armor_break": 3.0,
							"armor_break_time": 4.0,
							"hits_burrowed": true,
						},
						"add": {},
					},
					{
						"name": "Deep Fuse",
						"cost": 250,
						"blurb": "A deeper fuse drives the shell further before it goes off, for more damage.",
						"set": {},
						"add": {
							"damage": 10.0,
						},
					},
					{
						"name": "Penetrator Tip",
						"cost": 300,
						"blurb": "Penetrator tips strip one more point of armor from everything in the blast.",
						"set": {},
						"add": {
							"armor_break": 1.0,
						},
					},
					{
						"name": "Twin Charges",
						"cost": 450,
						"blurb": "Two charges per shell: faster fire and a wider shockwave underground.",
						"set": {},
						"add": {
							"splash": 8.0,
							"rate": 0.1,
						},
					},
				],
				"mastery": {
					"name": "Seismic Charge",
					"cost": 510,
					"blurb": "Collapses tunnels: burrowed enemies in the blast are forced up and can't dig again for 4 s.",
					"set": {
						"damage": 130.0,
						"range": 165.0,
						"rate": 0.85,
						"splash": 80.0,
						"armor_break": 6.0,
						"armor_break_time": 5.0,
						"hits_burrowed": true,
						"unearth": 4.0,
					},
					"add": {},
				},
			},
		],
	},
	"frost": {
		"name": "Cryo Emitter",
		"key": "3",
		"tiers": [
			{
				"name": "Cryo Emitter",
				"cost": 70,
				"blurb": "Pulses a freezing field that slows every enemy in range and deals light damage.",
				"set": {
					"damage": 3.0,
					"range": 105.0,
					"slow": 0.35,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 90,
				"blurb": "A stronger coolant loop: a deeper slow over a wider field.",
				"set": {
					"damage": 6.0,
					"range": 118.0,
					"slow": 0.45,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "stasis",
				"attack": false,
				"nodes": [
					{
						"name": "Stasis Field",
						"cost": 150,
						"blurb": "Near-freezing slow over a wide area.",
						"set": {
							"damage": 10.0,
							"range": 145.0,
							"slow": 0.65,
						},
						"add": {},
					},
					{
						"name": "Wider Coils",
						"cost": 180,
						"blurb": "Wider emitter coils stretch the stasis field.",
						"set": {},
						"add": {
							"range": 10.0,
						},
					},
					{
						"name": "Deep Chill",
						"cost": 220,
						"blurb": "A deeper chill: enemies stay slowed 0.3 s longer after each pulse.",
						"set": {},
						"add": {
							"slow_time": 0.3,
						},
					},
					{
						"name": "Cryo Pumps",
						"cost": 320,
						"blurb": "Upgraded cryo pumps: a much wider field and ice spikes that hurt a little more.",
						"set": {},
						"add": {
							"damage": 4.0,
							"range": 15.0,
						},
					},
				],
				"mastery": {
					"name": "Absolute Zero",
					"cost": 380,
					"blurb": "The maximum slow over the widest field in the arsenal.",
					"set": {
						"damage": 22.0,
						"range": 185.0,
						"slow": 0.7,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "shatter",
				"attack": false,
				"nodes": [
					{
						"name": "Shatter Field",
						"cost": 150,
						"blurb": "Chilled enemies take more damage from every source.",
						"set": {
							"damage": 12.0,
							"range": 132.0,
							"slow": 0.5,
							"vuln": 0.25,
						},
						"add": {},
					},
					{
						"name": "Brittle Frost",
						"cost": 180,
						"blurb": "Brittle frost makes chilled enemies take 5% more damage from everything.",
						"set": {},
						"add": {
							"vuln": 0.05,
						},
					},
					{
						"name": "Fast Freeze",
						"cost": 220,
						"blurb": "Faster freezing cycles: the field pulses more often.",
						"set": {},
						"add": {
							"rate": 0.15,
						},
					},
					{
						"name": "Crystal Lattice",
						"cost": 320,
						"blurb": "A crystal lattice: wider reach, harder hits and even more damage taken.",
						"set": {},
						"add": {
							"range": 8.0,
							"vuln": 0.05,
							"damage": 3.0,
						},
					},
				],
				"mastery": {
					"name": "Cryo Fracture",
					"cost": 380,
					"blurb": "Chilled enemies take far more damage from every source.",
					"set": {
						"damage": 24.0,
						"range": 150.0,
						"slow": 0.55,
						"vuln": 0.45,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "cryolock",
				"attack": false,
				"nodes": [
					{
						"name": "Cryo Lock",
						"cost": 150,
						"blurb": "Freezes repair systems: enemies in the field can't regenerate or be healed.",
						"set": {
							"damage": 8.0,
							"range": 130.0,
							"slow": 0.45,
							"block_repair": true,
						},
						"add": {},
					},
					{
						"name": "Circuit Frost",
						"cost": 180,
						"blurb": "Frost creeps into circuits further out: a wider lock field.",
						"set": {},
						"add": {
							"range": 10.0,
						},
					},
					{
						"name": "Lingering Lock",
						"cost": 220,
						"blurb": "The lock lingers: repairs stay frozen for 1 s after an enemy leaves the field.",
						"set": {
							"linger": 1.0,
						},
						"add": {},
					},
					{
						"name": "Iced Relays",
						"cost": 320,
						"blurb": "Iced relays: a deeper slow, a wider field and harder frost.",
						"set": {},
						"add": {
							"slow": 0.05,
							"range": 10.0,
							"damage": 4.0,
						},
					},
				],
				"mastery": {
					"name": "Permafrost",
					"cost": 380,
					"blurb": "Barriers stop recharging too, and locked enemies take extra damage.",
					"set": {
						"damage": 16.0,
						"range": 160.0,
						"slow": 0.55,
						"vuln": 0.15,
						"block_repair": true,
						"block_barrier": true,
					},
					"add": {},
				},
			},
		],
	},
	"sniper": {
		"name": "Railgun",
		"key": "4",
		"tiers": [
			{
				"name": "Railgun",
				"cost": 120,
				"blurb": "Fires a magnetic slug at extreme range that ignores armor.",
				"set": {
					"damage": 55.0,
					"range": 290.0,
					"rate": 0.45,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 150,
				"blurb": "Longer rails: much heavier slugs with even more range.",
				"set": {
					"damage": 105.0,
					"range": 330.0,
					"rate": 0.5,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "deadeye",
				"attack": false,
				"nodes": [
					{
						"name": "Deadeye",
						"cost": 260,
						"blurb": "Longest range in the arsenal.",
						"set": {
							"damage": 170.0,
							"range": 420.0,
							"rate": 0.6,
							"boss_mult": 2.0,
						},
						"add": {},
					},
					{
						"name": "Match Slugs",
						"cost": 310,
						"blurb": "Precision-machined slugs for bigger hits.",
						"set": {},
						"add": {
							"damage": 25.0,
						},
					},
					{
						"name": "Stabilized Rails",
						"cost": 380,
						"blurb": "Stabilized rails hold their aim at even longer range.",
						"set": {},
						"add": {
							"range": 20.0,
						},
					},
					{
						"name": "Weak-Point Scan",
						"cost": 560,
						"blurb": "A weak-point scanner and faster capacitors: bosses take 2.3× damage and shots come quicker.",
						"set": {
							"boss_mult": 2.3,
						},
						"add": {
							"rate": 0.05,
						},
					},
				],
				"mastery": {
					"name": "Executioner",
					"cost": 630,
					"blurb": "Destroys any non-boss target left under 20% health.",
					"set": {
						"damage": 280.0,
						"range": 470.0,
						"rate": 0.7,
						"boss_mult": 2.5,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "lance",
				"attack": false,
				"nodes": [
					{
						"name": "Piercing Rail",
						"cost": 260,
						"blurb": "The slug punches through every enemy in a straight line.",
						"set": {
							"damage": 130.0,
							"range": 380.0,
							"rate": 0.6,
						},
						"add": {},
					},
					{
						"name": "Denser Slug",
						"cost": 310,
						"blurb": "A denser slug keeps more of its punch as it tears through the line.",
						"set": {},
						"add": {
							"damage": 20.0,
						},
					},
					{
						"name": "Longer Rails",
						"cost": 380,
						"blurb": "Longer rails extend the line of fire.",
						"set": {},
						"add": {
							"range": 20.0,
						},
					},
					{
						"name": "Wide Bore",
						"cost": 560,
						"blurb": "A wider bore and quicker charging: the line hits everything within 14 px and fires faster.",
						"set": {
							"rail_width": 14.0,
						},
						"add": {
							"rate": 0.05,
						},
					},
				],
				"mastery": {
					"name": "Ion Lance",
					"cost": 630,
					"blurb": "The line hits everything within 22 px of it.",
					"set": {
						"damage": 220.0,
						"range": 430.0,
						"rate": 0.75,
						"rail_width": 22.0,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "nullslug",
				"attack": false,
				"nodes": [
					{
						"name": "Null Slug",
						"cost": 260,
						"blurb": "Deletes the target's barrier and shuts off its abilities: healing, EMP, auras, spawns, blinking, burrowing and regeneration.",
						"set": {
							"damage": 150.0,
							"range": 360.0,
							"rate": 0.55,
							"suppress": 4.0,
							"strip": 1.0,
						},
						"add": {},
					},
					{
						"name": "Longer Jam",
						"cost": 310,
						"blurb": "The jamming charge lasts a second longer.",
						"set": {},
						"add": {
							"suppress": 1.0,
						},
					},
					{
						"name": "Hardened Slug",
						"cost": 380,
						"blurb": "A hardened core for more damage per slug.",
						"set": {},
						"add": {
							"damage": 25.0,
						},
					},
					{
						"name": "Wide Jam",
						"cost": 560,
						"blurb": "The jam bursts on impact, suppressing enemies within 30 px too, and the rails recharge faster.",
						"set": {
							"suppress_spread": 30.0,
						},
						"add": {
							"rate": 0.05,
						},
					},
				],
				"mastery": {
					"name": "Void Round",
					"cost": 630,
					"blurb": "Suppression lasts longer, spreads to nearby enemies, and strips crowd-control immunity.",
					"set": {
						"damage": 240.0,
						"range": 400.0,
						"rate": 0.65,
						"suppress": 8.0,
						"suppress_spread": 60.0,
						"strip": 1.0,
						"expose": true,
					},
					"add": {},
				},
			},
		],
	},
	"tesla": {
		"name": "Arc Coil",
		"key": "5",
		"tiers": [
			{
				"name": "Arc Coil",
				"cost": 130,
				"blurb": "Discharges lightning that leaps between nearby enemies. Barriers take double damage.",
				"set": {
					"damage": 16.0,
					"range": 118.0,
					"chains": 3.0,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 160,
				"blurb": "A stronger coil: harder arcs that jump to one more target.",
				"set": {
					"damage": 26.0,
					"range": 128.0,
					"chains": 4.0,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "storm",
				"attack": false,
				"nodes": [
					{
						"name": "Storm Coil",
						"cost": 280,
						"blurb": "Arcs leap further and lose less power per jump.",
						"set": {
							"damage": 36.0,
							"range": 145.0,
							"chains": 9.0,
						},
						"add": {},
					},
					{
						"name": "Extra Toroid",
						"cost": 340,
						"blurb": "An extra toroid ring lets each arc jump to one more enemy.",
						"set": {},
						"add": {
							"chains": 1.0,
						},
					},
					{
						"name": "Conductive Air",
						"cost": 410,
						"blurb": "Ionized air: arcs can leap 10 px further between targets.",
						"set": {},
						"add": {
							"chain_range": 10.0,
						},
					},
					{
						"name": "Twin Spires",
						"cost": 590,
						"blurb": "Twin spires: arcs hit harder and chain to two more enemies.",
						"set": {},
						"add": {
							"damage": 5.0,
							"chains": 2.0,
						},
					},
				],
				"mastery": {
					"name": "Tempest Coil",
					"cost": 660,
					"blurb": "Arcs barely weaken between jumps.",
					"set": {
						"damage": 55.0,
						"range": 160.0,
						"chains": 15.0,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "overload",
				"attack": false,
				"nodes": [
					{
						"name": "Overload",
						"cost": 280,
						"blurb": "Every arc stuns its targets (bosses 0.15 s).",
						"set": {
							"damage": 42.0,
							"range": 140.0,
							"chains": 5.0,
							"stun": 0.5,
						},
						"add": {},
					},
					{
						"name": "Capacitor Bank",
						"cost": 340,
						"blurb": "A larger capacitor bank puts more power behind every arc.",
						"set": {},
						"add": {
							"damage": 6.0,
						},
					},
					{
						"name": "Stun Tuning",
						"cost": 410,
						"blurb": "Tuned discharges keep their targets stunned 0.1 s longer.",
						"set": {},
						"add": {
							"stun": 0.1,
						},
					},
					{
						"name": "Faster Discharge",
						"cost": 590,
						"blurb": "Faster discharge cycles and one more jump per arc.",
						"set": {},
						"add": {
							"chains": 1.0,
							"rate": 0.1,
						},
					},
				],
				"mastery": {
					"name": "Supercharger",
					"cost": 660,
					"blurb": "Longer stuns and harder hits.",
					"set": {
						"damage": 64.0,
						"range": 155.0,
						"chains": 7.0,
						"stun": 0.8,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "ionstorm",
				"attack": true,
				"nodes": [
					{
						"name": "Ion Storm",
						"cost": 280,
						"blurb": "Instead of chaining, charges a storm field that damages everything inside, air and ground. Double damage to barriers.",
						"set": {
							"damage": 24.0,
							"range": 130.0,
							"rate": 2.0,
						},
						"add": {},
					},
					{
						"name": "Denser Ions",
						"cost": 340,
						"blurb": "Denser ions: the storm hits harder with every tick.",
						"set": {},
						"add": {
							"damage": 4.0,
						},
					},
					{
						"name": "Wider Front",
						"cost": 410,
						"blurb": "A wider storm front covers more of the lane.",
						"set": {},
						"add": {
							"range": 8.0,
						},
					},
					{
						"name": "Storm Front",
						"cost": 590,
						"blurb": "Static builds up: a wider, stronger storm, and enemies that stay 2 s take 15% more damage.",
						"set": {},
						"add": {
							"static_vuln": 0.15,
							"damage": 4.0,
							"range": 6.0,
						},
					},
				],
				"mastery": {
					"name": "Maelstrom",
					"cost": 660,
					"blurb": "A wider, stronger storm. Enemies inside can't receive Bulwark barriers.",
					"set": {
						"damage": 42.0,
						"range": 160.0,
						"rate": 2.0,
						"block_grants": true,
					},
					"add": {},
				},
			},
		],
	},
	"laser": {
		"name": "Laser Lance",
		"key": "6",
		"tiers": [
			{
				"name": "Laser Lance",
				"cost": 140,
				"blurb": "A continuous beam that ignores armor and grows stronger the longer it holds one target.",
				"set": {
					"damage": 22.0,
					"range": 125.0,
					"ramp": 2.0,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 150,
				"blurb": "A brighter emitter: more damage, more range and a higher ramp.",
				"set": {
					"damage": 36.0,
					"range": 135.0,
					"ramp": 2.5,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "prism",
				"attack": false,
				"nodes": [
					{
						"name": "Prism Array",
						"cost": 300,
						"blurb": "Splits into three beams (extra beams at 60% power).",
						"set": {
							"damage": 38.0,
							"range": 145.0,
							"beams": 3.0,
						},
						"add": {},
					},
					{
						"name": "Focusing Optics",
						"cost": 360,
						"blurb": "Focusing optics make every beam burn hotter.",
						"set": {},
						"add": {
							"damage": 5.0,
						},
					},
					{
						"name": "Fourth Facet",
						"cost": 440,
						"blurb": "A fourth facet splits off another beam.",
						"set": {},
						"add": {
							"beams": 1.0,
						},
					},
					{
						"name": "Brighter Split",
						"cost": 640,
						"blurb": "Brighter splits: the extra beams reach 70% power and ramp up faster.",
						"set": {
							"secondary_beam": 0.7,
						},
						"add": {
							"ramp_time": -0.5,
						},
					},
				],
				"mastery": {
					"name": "Refraction Grid",
					"cost": 720,
					"blurb": "Six beams on six targets.",
					"set": {
						"damage": 56.0,
						"range": 160.0,
						"beams": 6.0,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "focus",
				"attack": false,
				"nodes": [
					{
						"name": "Focus Lens",
						"cost": 300,
						"blurb": "Boss killer.",
						"set": {
							"damage": 50.0,
							"range": 150.0,
							"ramp": 4.0,
						},
						"add": {},
					},
					{
						"name": "Cooled Lens",
						"cost": 360,
						"blurb": "A cooled lens takes a hotter beam.",
						"set": {},
						"add": {
							"damage": 6.0,
						},
					},
					{
						"name": "Quick Lock",
						"cost": 440,
						"blurb": "Quicker lock-on: the beam reaches full power half a second sooner.",
						"set": {},
						"add": {
							"ramp_time": -0.5,
						},
					},
					{
						"name": "Overdrive Lens",
						"cost": 640,
						"blurb": "An overdrive lens ramps up to 5× on a single target and reaches further.",
						"set": {
							"ramp": 5.0,
						},
						"add": {
							"range": 10.0,
						},
					},
				],
				"mastery": {
					"name": "Singularity Lens",
					"cost": 720,
					"blurb": "Nothing survives a long lock.",
					"set": {
						"damage": 72.0,
						"range": 170.0,
						"ramp": 7.0,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "sweeper",
				"attack": true,
				"nodes": [
					{
						"name": "Sweeper",
						"cost": 300,
						"blurb": "The beam sweeps back and forth across an arc, burning every enemy it crosses.",
						"set": {
							"damage": 30.0,
							"range": 140.0,
							"sweep": 70.0,
							"ramp": 1.0,
						},
						"add": {},
					},
					{
						"name": "Wider Sweep",
						"cost": 360,
						"blurb": "The sweep covers 15° more of the lane.",
						"set": {},
						"add": {
							"sweep": 15.0,
						},
					},
					{
						"name": "Hotter Beam",
						"cost": 440,
						"blurb": "A hotter beam burns harder as it sweeps.",
						"set": {},
						"add": {
							"damage": 6.0,
						},
					},
					{
						"name": "Lingering Burn",
						"cost": 640,
						"blurb": "Faster sweeps, and every enemy the beam crosses keeps burning for a second.",
						"set": {
							"burn_dps": 10.0,
							"burn_time": 1.0,
						},
						"add": {
							"sweep_speed": 0.3,
						},
					},
				],
				"mastery": {
					"name": "Scythe Array",
					"cost": 720,
					"blurb": "Two counter-sweeping beams that burn through barriers at double rate.",
					"set": {
						"damage": 48.0,
						"range": 155.0,
						"beams": 2.0,
						"sweep": 120.0,
						"shield_mult": 2.0,
					},
					"add": {},
				},
			},
		],
	},
	"missile": {
		"name": "Missile Battery",
		"key": "7",
		"tiers": [
			{
				"name": "Missile Battery",
				"cost": 110,
				"blurb": "Fires homing missiles with a small blast. Flyers take double damage.",
				"set": {
					"damage": 18.0,
					"range": 190.0,
					"missiles": 2.0,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 140,
				"blurb": "A third launch tube and stronger warheads.",
				"set": {
					"damage": 26.0,
					"range": 200.0,
					"missiles": 3.0,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "swarm",
				"attack": false,
				"nodes": [
					{
						"name": "Swarm Pods",
						"cost": 260,
						"blurb": "Salvos spread across targets.",
						"set": {
							"damage": 24.0,
							"range": 210.0,
							"missiles": 5.0,
						},
						"add": {},
					},
					{
						"name": "Sixth Tube",
						"cost": 310,
						"blurb": "A sixth tube adds another missile to every salvo.",
						"set": {},
						"add": {
							"missiles": 1.0,
						},
					},
					{
						"name": "Better Seekers",
						"cost": 380,
						"blurb": "Better seekers lock on from further away.",
						"set": {},
						"add": {
							"range": 10.0,
						},
					},
					{
						"name": "Quick Reload",
						"cost": 560,
						"blurb": "Quicker reloads and shaped charges: faster salvos that hit harder.",
						"set": {},
						"add": {
							"damage": 3.0,
							"rate": 0.1,
						},
					},
				],
				"mastery": {
					"name": "Locust Swarm",
					"cost": 630,
					"blurb": "Eight missiles per salvo.",
					"set": {
						"damage": 30.0,
						"range": 230.0,
						"missiles": 8.0,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "hellfire",
				"attack": false,
				"nodes": [
					{
						"name": "Hellfire",
						"cost": 260,
						"blurb": "Heavy warheads with a big blast.",
						"set": {
							"damage": 65.0,
							"range": 215.0,
							"missiles": 2.0,
							"splash": 50.0,
							"air_mult": 3.0,
						},
						"add": {},
					},
					{
						"name": "Bigger Warheads",
						"cost": 310,
						"blurb": "Bigger warheads for much heavier hits.",
						"set": {},
						"add": {
							"damage": 12.0,
						},
					},
					{
						"name": "Wide Blast",
						"cost": 380,
						"blurb": "A wider blast radius on every warhead.",
						"set": {},
						"add": {
							"splash": 5.0,
						},
					},
					{
						"name": "Proximity Fuses",
						"cost": 560,
						"blurb": "Proximity fuses and a third tube: one more missile per salvo and a wider blast.",
						"set": {},
						"add": {
							"missiles": 1.0,
							"splash": 5.0,
						},
					},
				],
				"mastery": {
					"name": "Doomsday Warheads",
					"cost": 630,
					"blurb": "Colossal warheads.",
					"set": {
						"damage": 115.0,
						"range": 235.0,
						"missiles": 3.0,
						"splash": 70.0,
						"air_mult": 3.0,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "cluster",
				"attack": false,
				"nodes": [
					{
						"name": "Cluster Munitions",
						"cost": 260,
						"blurb": "Each missile bursts into bomblets that carpet the target area.",
						"set": {
							"damage": 20.0,
							"range": 205.0,
							"missiles": 3.0,
							"bomblets": 4.0,
							"bomblet_splash": 26.0,
						},
						"add": {},
					},
					{
						"name": "Fifth Bomblet",
						"cost": 310,
						"blurb": "Each missile carries one more bomblet.",
						"set": {},
						"add": {
							"bomblets": 1.0,
						},
					},
					{
						"name": "Wider Scatter",
						"cost": 380,
						"blurb": "Bomblets scatter wider and burst bigger.",
						"set": {},
						"add": {
							"bomblet_splash": 4.0,
						},
					},
					{
						"name": "Hot Bomblets",
						"cost": 560,
						"blurb": "Hot bomblets and a fourth tube: one more missile per salvo, hitting harder.",
						"set": {},
						"add": {
							"missiles": 1.0,
							"damage": 3.0,
						},
					},
				],
				"mastery": {
					"name": "Carpet Bomber",
					"cost": 630,
					"blurb": "More bomblets, and they ignore armor.",
					"set": {
						"damage": 26.0,
						"range": 225.0,
						"missiles": 4.0,
						"bomblets": 7.0,
						"bomblet_splash": 32.0,
						"pierce": true,
					},
					"add": {},
				},
			},
		],
	},
	"amp": {
		"name": "Amplifier Pylon",
		"key": "8",
		"tiers": [
			{
				"name": "Amplifier Pylon",
				"cost": 100,
				"blurb": "Broadcasts a power field that boosts the damage of towers inside it.",
				"set": {
					"range": 100.0,
					"buff_dmg": 0.15,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 120,
				"blurb": "A stronger broadcast over a wider field.",
				"set": {
					"range": 115.0,
					"buff_dmg": 0.25,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "overclock",
				"attack": false,
				"nodes": [
					{
						"name": "Overclock Pylon",
						"cost": 220,
						"blurb": "Nearby towers hit harder and faster.",
						"set": {
							"range": 125.0,
							"buff_dmg": 0.3,
							"buff_rate": 0.25,
						},
						"add": {},
					},
					{
						"name": "Tuned Relays",
						"cost": 260,
						"blurb": "Tuned relays make boosted towers fire 5% faster.",
						"set": {},
						"add": {
							"buff_rate": 0.05,
						},
					},
					{
						"name": "Wider Broadcast",
						"cost": 320,
						"blurb": "A wider broadcast reaches more towers.",
						"set": {},
						"add": {
							"range": 5.0,
						},
					},
					{
						"name": "Heat Sinks",
						"cost": 470,
						"blurb": "Heat sinks let boosted towers run hotter: +5% damage and +5% speed.",
						"set": {},
						"add": {
							"buff_dmg": 0.05,
							"buff_rate": 0.05,
						},
					},
				],
				"mastery": {
					"name": "Hypercore Pylon",
					"cost": 530,
					"blurb": "A hypercore overdrives every tower in the field: the biggest damage and speed boost in the arsenal.",
					"set": {
						"range": 140.0,
						"buff_dmg": 0.45,
						"buff_rate": 0.4,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "array",
				"attack": false,
				"nodes": [
					{
						"name": "Targeting Array",
						"cost": 220,
						"blurb": "Nearby towers hit harder and reach further.",
						"set": {
							"range": 125.0,
							"buff_dmg": 0.25,
							"buff_range": 0.25,
						},
						"add": {},
					},
					{
						"name": "Better Optics",
						"cost": 260,
						"blurb": "Better optics give boosted towers 5% more range.",
						"set": {},
						"add": {
							"buff_range": 0.05,
						},
					},
					{
						"name": "Wider Broadcast",
						"cost": 320,
						"blurb": "A wider broadcast reaches more towers.",
						"set": {},
						"add": {
							"range": 5.0,
						},
					},
					{
						"name": "Range Finders",
						"cost": 470,
						"blurb": "Range finders sharpen the fire control: +5% damage and +5% range.",
						"set": {},
						"add": {
							"buff_dmg": 0.05,
							"buff_range": 0.05,
						},
					},
				],
				"mastery": {
					"name": "Command Array",
					"cost": 530,
					"blurb": "A full command array: towers in the field hit far harder and reach far further.",
					"set": {
						"range": 145.0,
						"buff_dmg": 0.4,
						"buff_range": 0.4,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "suppression",
				"attack": false,
				"nodes": [
					{
						"name": "Suppression Pylon",
						"cost": 220,
						"blurb": "Jams enemy support inside its field: Rally haste, Bulwark barriers and Repair Bot heals don't work there.",
						"set": {
							"range": 125.0,
							"buff_dmg": 0.25,
							"jam": 1.0,
						},
						"add": {},
					},
					{
						"name": "Stronger Jam",
						"cost": 260,
						"blurb": "A stronger jammer covers a wider field.",
						"set": {},
						"add": {
							"range": 5.0,
						},
					},
					{
						"name": "Signal Noise",
						"cost": 320,
						"blurb": "Signal noise scrambles enemy drives: enemies in the field move 10% slower.",
						"set": {
							"field_slow": 0.1,
						},
						"add": {},
					},
					{
						"name": "Wide Jam",
						"cost": 470,
						"blurb": "A wider jamming field, and boosted towers hit 5% harder.",
						"set": {},
						"add": {
							"buff_dmg": 0.05,
							"range": 10.0,
						},
					},
				],
				"mastery": {
					"name": "Silence Pylon",
					"cost": 530,
					"blurb": "Also shuts down Jammer EMPs and Overmind or Leviathan launches inside the field.",
					"set": {
						"range": 150.0,
						"buff_dmg": 0.35,
						"jam": 2.0,
					},
					"add": {},
				},
			},
		],
	},
	"flak": {
		"name": "Flak Battery",
		"key": "9",
		"tiers": [
			{
				"name": "Flak Battery",
				"cost": 80,
				"blurb": "Anti-air cannon whose airbursts hit every flyer in the blast.",
				"set": {
					"damage": 16.0,
					"range": 175.0,
					"rate": 1.4,
					"splash": 38.0,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 100,
				"blurb": "Heavier shells, faster fire and a wider burst.",
				"set": {
					"damage": 28.0,
					"range": 190.0,
					"rate": 1.5,
					"splash": 42.0,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "skyshred",
				"attack": false,
				"nodes": [
					{
						"name": "Sky Shredder",
						"cost": 190,
						"blurb": "Twin autocannons: more than double the rate of fire.",
						"set": {
							"damage": 30.0,
							"range": 200.0,
							"rate": 3.2,
						},
						"add": {},
					},
					{
						"name": "Faster Feed",
						"cost": 230,
						"blurb": "A faster ammo feed keeps the cannons firing.",
						"set": {},
						"add": {
							"rate": 0.3,
						},
					},
					{
						"name": "Better Fuses",
						"cost": 280,
						"blurb": "Better fuses widen each airburst.",
						"set": {},
						"add": {
							"splash": 4.0,
						},
					},
					{
						"name": "Third Cannon",
						"cost": 400,
						"blurb": "A third cannon and a tracking radar: much faster fire at longer range.",
						"set": {},
						"add": {
							"range": 10.0,
							"rate": 0.5,
						},
					},
				],
				"mastery": {
					"name": "Aerial Denial",
					"cost": 450,
					"blurb": "Four autocannons saturate the sky.",
					"set": {
						"damage": 40.0,
						"range": 225.0,
						"rate": 4.6,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "burst",
				"attack": false,
				"nodes": [
					{
						"name": "Proximity Burst",
						"cost": 190,
						"blurb": "Heavy shells with a huge airburst.",
						"set": {
							"damage": 80.0,
							"range": 210.0,
							"rate": 1.2,
							"splash": 70.0,
						},
						"add": {},
					},
					{
						"name": "Heavier Shells",
						"cost": 230,
						"blurb": "Heavier shells for bigger airbursts.",
						"set": {},
						"add": {
							"damage": 15.0,
						},
					},
					{
						"name": "Wider Burst",
						"cost": 280,
						"blurb": "Wider bursts catch more of a swarm.",
						"set": {},
						"add": {
							"splash": 5.0,
						},
					},
					{
						"name": "Auto-Loader",
						"cost": 400,
						"blurb": "An auto-loader and a tracking radar: faster fire at longer range.",
						"set": {},
						"add": {
							"range": 10.0,
							"rate": 0.1,
						},
					},
				],
				"mastery": {
					"name": "Thunderhead",
					"cost": 450,
					"blurb": "Massive airbursts that also stun flyers.",
					"set": {
						"damage": 150.0,
						"range": 240.0,
						"rate": 1.4,
						"splash": 90.0,
						"stun": 0.5,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "dualpurpose",
				"attack": false,
				"nodes": [
					{
						"name": "Dual Purpose",
						"cost": 190,
						"blurb": "Timed fuses: airbursts also hit ground enemies at reduced damage.",
						"set": {
							"damage": 34.0,
							"range": 195.0,
							"rate": 1.3,
							"splash": 45.0,
							"ground_mult": 0.6,
						},
						"add": {},
					},
					{
						"name": "Ground Fuses",
						"cost": 230,
						"blurb": "Better ground fuses: airbursts hit ground enemies at 70%.",
						"set": {
							"ground_mult": 0.7,
						},
						"add": {},
					},
					{
						"name": "Bigger Shells",
						"cost": 280,
						"blurb": "Bigger shells hit harder in the air and on the ground.",
						"set": {},
						"add": {
							"damage": 6.0,
						},
					},
					{
						"name": "Rapid Feed",
						"cost": 400,
						"blurb": "A rapid feed and wider bursts: faster fire, and ground enemies take 80%.",
						"set": {
							"ground_mult": 0.8,
						},
						"add": {
							"splash": 6.0,
							"rate": 0.2,
						},
					},
				],
				"mastery": {
					"name": "Flak Curtain",
					"cost": 450,
					"blurb": "Full damage to ground targets, and every burst shreds 2 armor.",
					"set": {
						"damage": 54.0,
						"range": 215.0,
						"rate": 1.6,
						"splash": 64.0,
						"shred": 2.0,
						"shred_max": 12.0,
						"ground_mult": 1.0,
					},
					"add": {},
				},
			},
		],
	},
	"sensor": {
		"name": "Sensor Array",
		"key": "0",
		"tiers": [
			{
				"name": "Sensor Array",
				"cost": 75,
				"blurb": "A radar dish that reveals cloaked enemies in its field and marks them to take extra damage.",
				"set": {
					"range": 130.0,
					"mark": 0.08,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 90,
				"blurb": "A bigger dish: a wider field and a stronger mark.",
				"set": {
					"range": 150.0,
					"mark": 0.12,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "deepscan",
				"attack": false,
				"nodes": [
					{
						"name": "Deep Scan",
						"cost": 160,
						"blurb": "The widest reveal field.",
						"set": {
							"range": 210.0,
							"mark": 0.14,
						},
						"add": {},
					},
					{
						"name": "Bigger Dish",
						"cost": 190,
						"blurb": "A bigger dish scans a wider field.",
						"set": {},
						"add": {
							"range": 15.0,
						},
					},
					{
						"name": "Signal Boost",
						"cost": 230,
						"blurb": "A signal booster strengthens the mark.",
						"set": {},
						"add": {
							"mark": 0.01,
						},
					},
					{
						"name": "Dual Dish",
						"cost": 340,
						"blurb": "A second dish: a much wider field and a stronger mark.",
						"set": {},
						"add": {
							"range": 15.0,
							"mark": 0.02,
						},
					},
				],
				"mastery": {
					"name": "Omniscient Grid",
					"cost": 380,
					"blurb": "Sees nearly half the sector at once.",
					"set": {
						"range": 280.0,
						"mark": 0.2,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "painter",
				"attack": false,
				"nodes": [
					{
						"name": "Target Painter",
						"cost": 160,
						"blurb": "Laser designators: marked enemies take more damage.",
						"set": {
							"range": 160.0,
							"mark": 0.25,
						},
						"add": {},
					},
					{
						"name": "Brighter Lasers",
						"cost": 190,
						"blurb": "Brighter lasers make marked enemies take 3% more damage.",
						"set": {},
						"add": {
							"mark": 0.03,
						},
					},
					{
						"name": "Wider Beam",
						"cost": 230,
						"blurb": "A wider painting beam covers more of the lane.",
						"set": {},
						"add": {
							"range": 5.0,
						},
					},
					{
						"name": "Twin Designators",
						"cost": 340,
						"blurb": "Twin designators: a stronger mark that stays on for 1 s after an enemy leaves the field.",
						"set": {
							"linger": 1.0,
						},
						"add": {
							"mark": 0.04,
						},
					},
				],
				"mastery": {
					"name": "Kill Beacon",
					"cost": 380,
					"blurb": "Marked enemies take far more damage from everything.",
					"set": {
						"range": 175.0,
						"mark": 0.4,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "disruptor",
				"attack": false,
				"nodes": [
					{
						"name": "Disruptor",
						"cost": 160,
						"blurb": "Jams movement tricks in its field: no burrowing, no blinking, and cloaks fail.",
						"set": {
							"range": 150.0,
							"mark": 0.12,
							"disrupt": true,
						},
						"add": {},
					},
					{
						"name": "Wider Jam",
						"cost": 190,
						"blurb": "The jamming field reaches further.",
						"set": {},
						"add": {
							"range": 10.0,
						},
					},
					{
						"name": "Echo Scan",
						"cost": 230,
						"blurb": "Echo scans keep cloaked enemies revealed for 1 s after they leave the field.",
						"set": {
							"linger": 1.0,
						},
						"add": {},
					},
					{
						"name": "Long Jam",
						"cost": 340,
						"blurb": "A long-range jammer: a much wider field and a stronger mark.",
						"set": {},
						"add": {
							"mark": 0.03,
							"range": 15.0,
						},
					},
				],
				"mastery": {
					"name": "Blackout Grid",
					"cost": 380,
					"blurb": "Also strips crowd-control immunity (Rampart, Colossus) inside the field.",
					"set": {
						"range": 200.0,
						"mark": 0.18,
						"disrupt": true,
						"expose": true,
					},
					"add": {},
				},
			},
		],
	},
	"gravity": {
		"name": "Graviton Projector",
		"key": "-",
		"tiers": [
			{
				"name": "Graviton Projector",
				"cost": 150,
				"blurb": "Gravity pulses shove ground enemies back down the lane and crush them.",
				"set": {
					"damage": 12.0,
					"range": 105.0,
					"push": 40.0,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 160,
				"blurb": "A stronger core: bigger shoves and harder pulses.",
				"set": {
					"damage": 22.0,
					"range": 115.0,
					"push": 52.0,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "repulsor",
				"attack": false,
				"nodes": [
					{
						"name": "Repulsor",
						"cost": 290,
						"blurb": "Violent pulses hurl enemies back down the lane.",
						"set": {
							"damage": 30.0,
							"range": 125.0,
							"push": 85.0,
						},
						"add": {},
					},
					{
						"name": "Denser Core",
						"cost": 350,
						"blurb": "A denser core throws enemies 10 px further.",
						"set": {},
						"add": {
							"push": 10.0,
						},
					},
					{
						"name": "Wider Field",
						"cost": 420,
						"blurb": "A wider field catches more of the lane.",
						"set": {},
						"add": {
							"range": 5.0,
						},
					},
					{
						"name": "Faster Pulses",
						"cost": 620,
						"blurb": "Faster pulses that also crush harder.",
						"set": {},
						"add": {
							"damage": 8.0,
							"rate": 0.03,
						},
					},
				],
				"mastery": {
					"name": "Singularity Engine",
					"cost": 690,
					"blurb": "Throws whole columns of enemies back.",
					"set": {
						"damage": 55.0,
						"range": 140.0,
						"rate": 0.36,
						"push": 130.0,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "crush",
				"attack": false,
				"nodes": [
					{
						"name": "Crush Field",
						"cost": 290,
						"blurb": "Crushing gravity: heavy damage and a stun.",
						"set": {
							"damage": 75.0,
							"range": 120.0,
							"push": 30.0,
							"stun": 0.6,
						},
						"add": {},
					},
					{
						"name": "Heavier Field",
						"cost": 350,
						"blurb": "A heavier field crushes harder.",
						"set": {},
						"add": {
							"damage": 12.0,
						},
					},
					{
						"name": "Lasting Pin",
						"cost": 420,
						"blurb": "A lasting pin keeps enemies stunned 0.1 s longer.",
						"set": {},
						"add": {
							"stun": 0.1,
						},
					},
					{
						"name": "Faster Pulses",
						"cost": 620,
						"blurb": "Faster pulses over a wider field.",
						"set": {},
						"add": {
							"range": 5.0,
							"rate": 0.03,
						},
					},
				],
				"mastery": {
					"name": "Event Horizon",
					"cost": 690,
					"blurb": "Pins everything in the field and crushes it.",
					"set": {
						"damage": 135.0,
						"range": 135.0,
						"rate": 0.5,
						"stun": 1.0,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "well",
				"attack": true,
				"nodes": [
					{
						"name": "Gravity Well",
						"cost": 290,
						"blurb": "Pulls enemies toward one point on the lane, bunching them up for splash towers.",
						"set": {
							"damage": 25.0,
							"range": 125.0,
							"pull": 50.0,
							"slow": 0.2,
						},
						"add": {},
					},
					{
						"name": "Deeper Well",
						"cost": 350,
						"blurb": "A deeper well pulls enemies 10 px further.",
						"set": {},
						"add": {
							"pull": 10.0,
						},
					},
					{
						"name": "Heavier Hold",
						"cost": 420,
						"blurb": "A heavier hold slows held enemies 5% more.",
						"set": {},
						"add": {
							"slow": 0.05,
						},
					},
					{
						"name": "Crushing Grip",
						"cost": 620,
						"blurb": "A crushing grip over a wider well: held enemies take more damage.",
						"set": {},
						"add": {
							"range": 5.0,
							"damage": 10.0,
						},
					},
				],
				"mastery": {
					"name": "Collapse Point",
					"cost": 690,
					"blurb": "Every third pulse implodes for 6% of max HP on everything held (bosses 1.5%).",
					"set": {
						"damage": 45.0,
						"range": 140.0,
						"pull": 75.0,
						"implode_every": 3.0,
						"implode_pct": 0.06,
					},
					"add": {},
				},
			},
		],
	},
	"nullifier": {
		"name": "Nullifier",
		"key": "=",
		"tiers": [
			{
				"name": "Nullifier",
				"cost": 120,
				"blurb": "Pulses a dampening field that strips away part of every enemy barrier inside it.",
				"set": {
					"damage": 5.0,
					"range": 110.0,
					"rate": 0.5,
					"strip": 0.4,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 130,
				"blurb": "Enemies in the field lose crowd-control immunity.",
				"set": {
					"damage": 8.0,
					"range": 120.0,
					"rate": 0.5882,
					"strip": 0.6,
					"expose": true,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "purge",
				"attack": false,
				"nodes": [
					{
						"name": "Purge Emitter",
						"cost": 240,
						"blurb": "Wipes barriers clean and weakens armor while enemies stay in the field.",
						"set": {
							"damage": 10.0,
							"range": 130.0,
							"strip": 1.0,
							"armor_field": 3.0,
							"expose": true,
						},
						"add": {},
					},
					{
						"name": "Wider Emitter",
						"cost": 290,
						"blurb": "A wider emitter covers more of the lane.",
						"set": {},
						"add": {
							"range": 8.0,
						},
					},
					{
						"name": "Deep Purge",
						"cost": 350,
						"blurb": "A deeper purge strips one more point of armor inside the field.",
						"set": {},
						"add": {
							"armor_break": 1.0,
						},
					},
					{
						"name": "Long Emitter",
						"cost": 510,
						"blurb": "A faster cycle and a longer emitter: pulses every 1.4 s over a wider field.",
						"set": {
							"rate": 0.7143,
						},
						"add": {
							"range": 8.0,
						},
					},
				],
				"mastery": {
					"name": "Absolute Null",
					"cost": 570,
					"blurb": "Barriers can't re-form inside the field at all.",
					"set": {
						"damage": 16.0,
						"range": 155.0,
						"armor_field": 7.0,
						"expose": true,
						"block_barrier": true,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "dampener",
				"attack": false,
				"nodes": [
					{
						"name": "Dampener",
						"cost": 240,
						"blurb": "Shuts off every enemy ability in the field: healing, auras, EMP, spawns, blinking, burrowing, regeneration.",
						"set": {
							"damage": 8.0,
							"range": 130.0,
							"dampen": true,
							"expose": true,
						},
						"add": {},
					},
					{
						"name": "Wider Dampening",
						"cost": 290,
						"blurb": "A wider dampening field silences more enemies.",
						"set": {},
						"add": {
							"range": 8.0,
						},
					},
					{
						"name": "Lingering Silence",
						"cost": 350,
						"blurb": "Silence lingers on enemies for 1 s after they leave the field.",
						"set": {
							"linger": 1.0,
						},
						"add": {},
					},
					{
						"name": "Long Dampening",
						"cost": 510,
						"blurb": "A faster cycle and a longer reach: pulses every 1.4 s over a wider field.",
						"set": {
							"rate": 0.7143,
						},
						"add": {
							"range": 8.0,
						},
					},
				],
				"mastery": {
					"name": "Silence Engine",
					"cost": 570,
					"blurb": "Suppression follows enemies out of the field, and works on bosses at half strength.",
					"set": {
						"damage": 14.0,
						"range": 155.0,
						"linger": 3.0,
						"expose": true,
						"suppress_boss": 0.5,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "feedback",
				"attack": false,
				"nodes": [
					{
						"name": "Feedback Loop",
						"cost": 240,
						"blurb": "Barrier it strips is dealt back to the enemy's hull as damage.",
						"set": {
							"damage": 8.0,
							"range": 125.0,
							"strip": 0.6,
							"expose": true,
							"feedback": 1.0,
						},
						"add": {},
					},
					{
						"name": "Stronger Pull",
						"cost": 290,
						"blurb": "A stronger pull strips 70% of each barrier.",
						"set": {
							"strip": 0.7,
						},
						"add": {},
					},
					{
						"name": "Amplified Return",
						"cost": 350,
						"blurb": "Amplified feedback returns 125% of each stripped barrier as damage.",
						"set": {
							"feedback": 1.25,
						},
						"add": {},
					},
					{
						"name": "Wider Loop",
						"cost": 510,
						"blurb": "A faster, wider loop: pulses every 1.4 s over a bigger field.",
						"set": {
							"rate": 0.7143,
						},
						"add": {
							"range": 10.0,
						},
					},
				],
				"mastery": {
					"name": "Overload Cascade",
					"cost": 570,
					"blurb": "Stripped barriers also detonate for 50% as splash (60 px).",
					"set": {
						"damage": 14.0,
						"range": 145.0,
						"strip": 0.85,
						"expose": true,
						"feedback": 1.25,
						"cascade": 0.5,
						"cascade_radius": 60.0,
					},
					"add": {},
				},
			},
		],
	},
	"nova": {
		"name": "Nova Reactor",
		"key": "[",
		"tiers": [
			{
				"name": "Nova Reactor",
				"cost": 160,
				"blurb": "A reactor that releases a shockwave all around it, hitting every enemy in range, air and ground.",
				"set": {
					"damage": 30.0,
					"range": 100.0,
					"rate": 0.5,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 170,
				"blurb": "A hotter core: stronger, wider and slightly faster waves.",
				"set": {
					"damage": 50.0,
					"range": 110.0,
					"rate": 0.55,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "supernova",
				"attack": false,
				"nodes": [
					{
						"name": "Supernova",
						"cost": 300,
						"blurb": "Slow, devastating shockwaves.",
						"set": {
							"damage": 120.0,
							"range": 125.0,
							"rate": 0.4,
						},
						"add": {},
					},
					{
						"name": "Denser Core",
						"cost": 360,
						"blurb": "A denser core puts more power into each wave.",
						"set": {},
						"add": {
							"damage": 20.0,
						},
					},
					{
						"name": "Wider Wave",
						"cost": 440,
						"blurb": "Each wave reaches further.",
						"set": {},
						"add": {
							"range": 8.0,
						},
					},
					{
						"name": "Overcharged Core",
						"cost": 640,
						"blurb": "An overcharged core: much stronger waves, released a little faster.",
						"set": {},
						"add": {
							"rate": 0.05,
							"damage": 30.0,
						},
					},
				],
				"mastery": {
					"name": "Hypernova",
					"cost": 720,
					"blurb": "Each wave also shatters half of every barrier it hits.",
					"set": {
						"damage": 220.0,
						"range": 150.0,
						"rate": 0.45,
						"strip": 0.5,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "pulsereactor",
				"attack": false,
				"nodes": [
					{
						"name": "Pulse Reactor",
						"cost": 300,
						"blurb": "Rapid low-power rings that shred swarms.",
						"set": {
							"damage": 34.0,
							"range": 110.0,
							"rate": 1.2,
						},
						"add": {},
					},
					{
						"name": "Faster Cycling",
						"cost": 360,
						"blurb": "Faster cycling releases more rings per second.",
						"set": {},
						"add": {
							"rate": 0.15,
						},
					},
					{
						"name": "Stronger Rings",
						"cost": 440,
						"blurb": "Each ring hits harder.",
						"set": {},
						"add": {
							"damage": 5.0,
						},
					},
					{
						"name": "Overclocked Cycling",
						"cost": 640,
						"blurb": "Overclocked cycling: faster rings that reach further.",
						"set": {},
						"add": {
							"range": 6.0,
							"rate": 0.15,
						},
					},
				],
				"mastery": {
					"name": "Chain Reactor",
					"cost": 720,
					"blurb": "Every kill sets off a 40 px mini-nova.",
					"set": {
						"damage": 48.0,
						"range": 120.0,
						"rate": 1.7,
						"mini_nova": 40.0,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "solarflare",
				"attack": false,
				"nodes": [
					{
						"name": "Solar Flare",
						"cost": 300,
						"blurb": "Waves leave the ground burning, ignoring armor.",
						"set": {
							"damage": 50.0,
							"range": 115.0,
							"rate": 0.55,
							"burn_dps": 20.0,
							"burn_time": 2.0,
						},
						"add": {},
					},
					{
						"name": "Hotter Flares",
						"cost": 360,
						"blurb": "Hotter flares make the burning ground hurt more.",
						"set": {},
						"add": {
							"burn_dps": 6.0,
						},
					},
					{
						"name": "Longer Burn",
						"cost": 440,
						"blurb": "The ground keeps burning for an extra second.",
						"set": {},
						"add": {
							"burn_time": 1.0,
						},
					},
					{
						"name": "Plasma Core",
						"cost": 640,
						"blurb": "A plasma core: stronger, wider waves and hotter flames.",
						"set": {},
						"add": {
							"range": 6.0,
							"damage": 10.0,
							"burn_dps": 6.0,
						},
					},
				],
				"mastery": {
					"name": "Corona",
					"cost": 720,
					"blurb": "A constant burning aura around the reactor, on top of its waves.",
					"set": {
						"damage": 65.0,
						"range": 130.0,
						"rate": 0.55,
						"aura_dps": 45.0,
					},
					"add": {},
				},
			},
		],
	},
	"drones": {
		"name": "Drone Bay",
		"key": "]",
		"tiers": [
			{
				"name": "Drone Bay",
				"cost": 180,
				"blurb": "Launches combat drones that hunt enemies anywhere on the map.",
				"set": {
					"drones": 2.0,
					"damage": 12.0,
					"rate": 3.0,
					"drone_speed": 160.0,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 170,
				"blurb": "A bigger hangar: one more drone, and all of them hit harder.",
				"set": {
					"drones": 3.0,
					"damage": 16.0,
					"rate": 3.0,
					"drone_speed": 170.0,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "interceptors",
				"attack": false,
				"nodes": [
					{
						"name": "Interceptor Wing",
						"cost": 300,
						"blurb": "Fast interceptors that hunt flyers first.",
						"set": {
							"drones": 5.0,
							"damage": 16.0,
							"rate": 4.0,
							"drone_speed": 220.0,
							"air_mult": 2.0,
						},
						"add": {},
					},
					{
						"name": "Sixth Drone",
						"cost": 360,
						"blurb": "A sixth interceptor joins the wing.",
						"set": {},
						"add": {
							"drones": 1.0,
						},
					},
					{
						"name": "Afterburners",
						"cost": 440,
						"blurb": "Afterburners get the interceptors to their targets faster.",
						"set": {},
						"add": {
							"drone_speed": 30.0,
						},
					},
					{
						"name": "Seventh Drone",
						"cost": 640,
						"blurb": "A seventh interceptor, and better guns for the whole wing.",
						"set": {},
						"add": {
							"damage": 3.0,
							"drones": 1.0,
						},
					},
				],
				"mastery": {
					"name": "Swarm Carrier",
					"cost": 720,
					"blurb": "A full carrier deck: nine interceptors that shred flyers anywhere on the map.",
					"set": {
						"drones": 9.0,
						"damage": 20.0,
						"rate": 4.5,
						"drone_speed": 250.0,
						"air_mult": 2.0,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "bombers",
				"attack": true,
				"nodes": [
					{
						"name": "Bomber Wing",
						"cost": 300,
						"blurb": "Heavy drones that carpet ground enemies.",
						"set": {
							"bombers": 2.0,
							"bomb_damage": 60.0,
							"splash": 40.0,
							"ground_only": true,
						},
						"add": {},
					},
					{
						"name": "Bigger Bombs",
						"cost": 360,
						"blurb": "Bigger bombs for heavier hits.",
						"set": {},
						"add": {
							"bomb_damage": 15.0,
						},
					},
					{
						"name": "Wider Blast",
						"cost": 440,
						"blurb": "A wider blast from every bomb.",
						"set": {},
						"add": {
							"splash": 5.0,
						},
					},
					{
						"name": "Faster Rearm",
						"cost": 640,
						"blurb": "A third bomber, and faster rearming for the whole wing.",
						"set": {},
						"add": {
							"bombers": 1.0,
							"rate_pct": 0.25,
						},
					},
				],
				"mastery": {
					"name": "Strike Wing",
					"cost": 720,
					"blurb": "Bombs also hit burrowed enemies.",
					"set": {
						"bombers": 4.0,
						"bomb_damage": 100.0,
						"splash": 52.0,
						"hits_burrowed": true,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "hunters",
				"attack": false,
				"nodes": [
					{
						"name": "Hunter-Killer",
						"cost": 300,
						"blurb": "Hunts specialists first (Stalker, Rally Beacon, Bulwark, Mender, Jammer, Repair Bot) and marks them.",
						"set": {
							"drones": 3.0,
							"damage": 20.0,
							"mark": 0.2,
							"hunt": true,
						},
						"add": {},
					},
					{
						"name": "Fourth Drone",
						"cost": 360,
						"blurb": "A fourth hunter-killer joins the pack.",
						"set": {},
						"add": {
							"drones": 1.0,
						},
					},
					{
						"name": "Target Database",
						"cost": 440,
						"blurb": "An updated target database: the drones also go for Phantoms and Gunships first.",
						"set": {
							"hunt_extra": true,
						},
						"add": {},
					},
					{
						"name": "Stronger Marks",
						"cost": 640,
						"blurb": "Stronger marks and better guns: marked enemies take 25% more damage.",
						"set": {
							"mark": 0.25,
						},
						"add": {
							"damage": 4.0,
						},
					},
				],
				"mastery": {
					"name": "Assassin Protocol",
					"cost": 720,
					"blurb": "A drone locked on a target also suppresses its abilities.",
					"set": {
						"drones": 5.0,
						"damage": 30.0,
						"mark": 0.3,
						"hunt": true,
						"suppress_hit": true,
					},
					"add": {},
				},
			},
		],
	},
	"scrap": {
		"name": "Scrapyard",
		"key": "\\",
		"tiers": [
			{
				"name": "Scrapyard",
				"cost": 150,
				"blurb": "A salvage yard that strips wrecks for parts and pays out credits every time a round is cleared.",
				"set": {
					"income": 25.0,
				},
				"add": {},
			},
			{
				"name": "Retrofit",
				"cost": 175,
				"blurb": "A second crusher line more than doubles the payout.",
				"set": {
					"income": 55.0,
				},
				"add": {},
			},
		],
		"branches": [
			{
				"key": "a",
				"id": "mint",
				"attack": false,
				"nodes": [
					{
						"name": "Credit Mint",
						"cost": 300,
						"blurb": "Presses salvage straight into credits: the biggest steady income.",
						"set": {
							"income": 110.0,
						},
						"add": {},
					},
					{
						"name": "Stamping Press",
						"cost": 320,
						"blurb": "A faster press turns out more credits each round.",
						"set": {},
						"add": {
							"income": 25.0,
						},
					},
					{
						"name": "Vault Doors",
						"cost": 380,
						"blurb": "Secure storage lets the mint run larger batches.",
						"set": {},
						"add": {
							"income": 30.0,
						},
					},
					{
						"name": "Treasury Link",
						"cost": 480,
						"blurb": "A direct line to command's treasury raises every payout.",
						"set": {},
						"add": {
							"income": 40.0,
						},
					},
				],
				"mastery": {
					"name": "Reserve Bank",
					"cost": 900,
					"blurb": "Also pays 3% interest on your banked credits at each round clear, up to 300.",
					"set": {
						"income": 250.0,
						"interest": 0.03,
						"interest_cap": 300.0,
					},
					"add": {},
				},
			},
			{
				"key": "b",
				"id": "collector",
				"attack": false,
				"nodes": [
					{
						"name": "Scrap Collector",
						"cost": 280,
						"blurb": "Magnet cranes sweep the lane: enemies destroyed in its field pay 25% more credits.",
						"set": {
							"range": 150.0,
							"bounty_bonus": 0.25,
						},
						"add": {},
					},
					{
						"name": "Magnet Cranes",
						"cost": 300,
						"blurb": "Longer crane arms reach further down the lane.",
						"set": {},
						"add": {
							"range": 25.0,
						},
					},
					{
						"name": "Sorting Line",
						"cost": 320,
						"blurb": "Sorts the wreckage for the valuable parts.",
						"set": {},
						"add": {
							"bounty_bonus": 0.1,
						},
					},
					{
						"name": "Smelter",
						"cost": 460,
						"blurb": "Melts scrap down on site: more credits from a wider field.",
						"set": {},
						"add": {
							"bounty_bonus": 0.1,
							"range": 25.0,
						},
					},
				],
				"mastery": {
					"name": "Reclamation Plant",
					"cost": 850,
					"blurb": "Enemies destroyed in its field pay 60% more, and bosses pay double.",
					"set": {
						"range": 200.0,
						"bounty_bonus": 0.6,
						"boss_bounty": 2.0,
					},
					"add": {},
				},
			},
			{
				"key": "c",
				"id": "depot",
				"attack": false,
				"nodes": [
					{
						"name": "Supply Depot",
						"cost": 280,
						"blurb": "Stockpiled parts: towers in its field upgrade for 10% less.",
						"set": {
							"range": 140.0,
							"discount": 0.1,
						},
						"add": {},
					},
					{
						"name": "Bulk Orders",
						"cost": 300,
						"blurb": "Buying in bulk cuts upgrade prices further.",
						"set": {},
						"add": {
							"discount": 0.05,
						},
					},
					{
						"name": "Freight Rail",
						"cost": 320,
						"blurb": "A rail spur delivers parts to more of the line.",
						"set": {},
						"add": {
							"range": 30.0,
						},
					},
					{
						"name": "Procurement Office",
						"cost": 460,
						"blurb": "Better contracts and a wider delivery area.",
						"set": {},
						"add": {
							"discount": 0.05,
							"range": 20.0,
						},
					},
				],
				"mastery": {
					"name": "Forward Command",
					"cost": 850,
					"blurb": "Towers in its field upgrade for 25% less and sell back for everything spent on them.",
					"set": {
						"range": 200.0,
						"discount": 0.25,
						"sell_field": 1.0,
					},
					"add": {},
				},
			},
		],
	},
}
